### *Exercici 1
##### - Carregar “data” i "features" del conjunt de dades, i visualitza els 10 primers registres de cadascun.


In [1]:
from sklearn.datasets import load_iris
data = load_iris()
import numpy as np  
datos_data = data.data
     
print(datos_data[:10])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [2]:
from sklearn.datasets import load_iris
data = load_iris()
import numpy as np  
datos_target = data.target
     
print(datos_target[:10])
    

[0 0 0 0 0 0 0 0 0 0]


  ### *Exercici 2
##### - Concatena “data” i “features” en un nou array. Mostra els 5 primers registres.


In [3]:
arr1 = np.array(datos_target)
arr2 = np.array(datos_data)

arr = np.column_stack((arr2, arr1))

print(arr[:5])


[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


### *Exercici 3
##### - Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.


###### MITJANA SÈPAL

In [4]:
i = 0
longitud_sepal =[fila[i] for fila in arr]
media_sepal = np.mean(longitud_sepal) 
round(media_sepal,2)


5.84

##### DESVIACIÓ SÈPAL

In [5]:
i = 0
longitud_sepal =[fila[i] for fila in arr]
desviacio_sepal = np.std(longitud_sepal) 
round(desviacio_sepal,2)


0.83

###### MITJANA PÈTAL

In [6]:
i = 2
longitud_petal =[fila[i] for fila in arr]
media_petal = np.mean(longitud_petal) 
round(media_petal,2)

3.76

##### DESVIACIÓ PÈTAL

In [7]:
i = 2
longitud_petal =[fila[i] for fila in arr]
desviacio_petal = np.std(longitud_petal) 
round(desviacio_petal,2)



1.76

### *Exercici 4

##### -Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.


In [8]:
from numpy import random

longitud_total = arr.shape[0]
indices_muestra = np.random.choice(longitud_total, 20, replace=False)
muestra_aleatoria = arr[indices_muestra]
print(muestra_aleatoria)

[[7.2 3.  5.8 1.6 2. ]
 [5.8 2.7 5.1 1.9 2. ]
 [6.7 3.1 5.6 2.4 2. ]
 [5.1 3.5 1.4 0.2 0. ]
 [6.7 3.3 5.7 2.1 2. ]
 [4.9 2.5 4.5 1.7 2. ]
 [4.8 3.  1.4 0.1 0. ]
 [5.7 2.8 4.5 1.3 1. ]
 [5.7 2.9 4.2 1.3 1. ]
 [6.3 2.9 5.6 1.8 2. ]
 [6.4 2.7 5.3 1.9 2. ]
 [5.5 4.2 1.4 0.2 0. ]
 [5.5 2.4 3.7 1.  1. ]
 [6.6 3.  4.4 1.4 1. ]
 [7.7 2.8 6.7 2.  2. ]
 [4.7 3.2 1.3 0.2 0. ]
 [6.4 3.1 5.5 1.8 2. ]
 [5.2 4.1 1.5 0.1 0. ]
 [5.1 2.5 3.  1.1 1. ]
 [5.7 3.  4.2 1.2 1. ]]


### *Exercici 5
##### -Crea una matriu que mostri: 
###### • La mitjana de cada característica per espècie. 
###### • La desviació estàndard de cada característica per espècie


In [9]:
list(data.target_names)
['setosa', 'versicolor', 'virginica']

['setosa', 'versicolor', 'virginica']

#### MITJANA

In [10]:
# Obtener los datos numéricos (primeras 4 columnas) y las especies (última columna)
numeric_data = arr[:, :4]
species = arr[:, 4]

# Obtener las especies únicas.
unique_species = np.unique(species)

# Crear una matriz para almacenar los resultados.
result = np.zeros((len(unique_species) + 1, numeric_data.shape[1] + 1), dtype=object)

# Llenar la primera fila con los encabezados de las columnas.
result[0, :-1] = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
result[0, -1] = 'Especies'

# Llenar la primera columna con los nombres de las especies.
result[1:, -1] = unique_species

# Calcular el promedio de cada columna por cada especie.
for i, specie in enumerate(unique_species):
    specie_indices = (species == specie)
    result[i + 1, :-1] = np.mean(numeric_data[specie_indices], axis=0)

print(result)




[['sepal length (cm)' 'sepal width (cm)' 'petal length (cm)'
  'petal width (cm)' 'Especies']
 [5.005999999999999 3.428000000000001 1.4620000000000002
  0.2459999999999999 0.0]
 [5.936 2.7700000000000005 4.26 1.3259999999999998 1.0]
 [6.587999999999998 2.9739999999999998 5.552 2.026 2.0]]


#### DESVIACIÓ

In [11]:
# Lo mismo para la desviació.

# Obtener los datos numéricos (primeras 4 columnas) y las especies (última columna)
numeric_data = arr[:, :4]
species = arr[:, 4]

# Obtener las especies únicas.
unique_species = np.unique(species)

# Crear una matriz para almacenar los resultados.
result = np.zeros((len(unique_species) + 1, numeric_data.shape[1] + 1), dtype=object)

# Llenar la primera fila con los encabezados de las columnas.
result[0, :-1] = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
result[0, -1] = 'Especies'

# Llenar la primera columna con los nombres de las especies.
result[1:, -1] = unique_species

# Calcular el promedio de cada columna por cada especie.
for i, specie in enumerate(unique_species):
    specie_indices = (species == specie)
    result[i + 1, :-1] = np.std(numeric_data[specie_indices], axis=0)

print(result)

[['sepal length (cm)' 'sepal width (cm)' 'petal length (cm)'
  'petal width (cm)' 'Especies']
 [0.348946987377739 0.3752545802518604 0.17191858538273286
  0.10432641084595984 0.0]
 [0.5109833656783752 0.31064449134018135 0.4651881339845204
  0.19576516544063702 1.0]
 [0.6294886813914925 0.319255383666431 0.5463478745268441
  0.2718896835115301 2.0]]


#### *Exercici 6
##### • Calcula la quantitat de mostres per espècie.
##### • Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"


In [12]:
especies = np.unique(arr[:, -1])

cantidad_muestras_por_especie = {especie: np.sum(arr[:, -1] == especie) for especie in especies}

print(cantidad_muestras_por_especie)

{0.0: 50, 1.0: 50, 2.0: 50}


In [13]:
# Variable columna de valores = 0{sepal length}

indice_columna_0 = 0

# Variable columna de valores = 4 {especies}

indice_columna_4 = 4

# Calculo de la media de la columna 0

media_columna_0 = np.mean(arr[:, indice_columna_0])

# Encontrar el indice del valor máximo de la media columna 0.

max_media_columna_0 = np.argmax(media_columna_0)

# Ahora encontrar la especie que correponda al máximo valor de la columna 0.

especie_max_media = arr[max_media_columna_0, indice_columna_4]

print(f'La especie que corresponde al valor máximo de la media de la columna del sepal length es: {especie_max_media}')




La especie que corresponde al valor máximo de la media de la columna del sepal length es: 0.0


### - Exercici 7
###### • Calcula la matriu de correlació entre les variables.
###### • Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 
###### • Troba la mostra amb els pètals més grans.


In [14]:
# Primero tengo que trasponer los datos de las columnas en filas
datos_traspuestos = arr.T

In [15]:
# correlacion
matriz_correlacion = np.corrcoef(datos_traspuestos)# Crea matriz de correlación.
print(matriz_correlacion)

[[ 1.         -0.11756978  0.87175378  0.81794113  0.78256123]
 [-0.11756978  1.         -0.4284401  -0.36612593 -0.42665756]
 [ 0.87175378 -0.4284401   1.          0.96286543  0.9490347 ]
 [ 0.81794113 -0.36612593  0.96286543  1.          0.95654733]
 [ 0.78256123 -0.42665756  0.9490347   0.95654733  1.        ]]


In [16]:
# valores mayor que la mitjana.

longitud_petals = np.array([arr])

mitjana_petals = np.mean(longituds_petals)


valors_major_que_mitjana = longitud_petals[longituds_petals > mitjana_petals]

print(valors_major_que_mitjana)

NameError: name 'longituds_petals' is not defined

In [ ]:

columna_longitud_petalo = 2

indice_fila_max_petalos = np.argmax(arr[:, columna_longitud_petalo])


muestra_max_petalos = arr[indice_fila_max_petalos]

print(muestra_max_petalos)

### - Exercici 8
##### Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.


In [ ]:
especies = arr[:, -1]
longitud_sepalos = arr[:, 0]
longitud_petalos = arr[:, 2]


longitud_mediana_sepalos = {}
longitud_mediana_petalos = {}

for especie in np.unique(especies):
    longitud_mediana_sepalos[especie] = np.mean(longitud_sepalos)
    longitud_mediana_petalos[especie] = np.mean(longitud_petalos)


diferencia_longitudes = {}

for especie in np.unique(especies):
        diferencia_longitudes[especie] = abs(longitud_mediana_sepalos[especie] - longitud_mediana_petalos[especie])


especie_max_diferencia = max(diferencia_longitudes, key=diferencia_longitudes.get)
maxima_diferencia = diferencia_longitudes[especie_max_diferencia]

print("Especie mayor diferencia:", especie_max_diferencia)
print("Diferencia más grande:", maxima_diferencia)