### *Exercici 1
##### - Carregar “data” i "features" del conjunt de dades, i visualitza els 10 primers registres de cadascun.


In [4]:
from sklearn.datasets import load_iris
data = load_iris()
import numpy as np  
datos_data = data.data
     
print(datos_data[:10])


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [5]:
from sklearn.datasets import load_iris
data = load_iris()
import numpy as np  
datos_target = data.target
     
print(datos_target[:10])
    

[0 0 0 0 0 0 0 0 0 0]


  ### *Exercici 2
##### - Concatena “data” i “features” en un nou array. Mostra els 5 primers registres.


In [6]:
arr1 = np.array(datos_target)
arr2 = np.array(datos_data)

arr = np.column_stack((arr2, arr1))

print(arr[:5])


[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]]


### *Exercici 3
##### - Calcula la mitjana i desviació estàndard de la longitud del sèpal ("sepal length (cm)") i la longitud del pètal ("petal length (cm)"). Mostra els resultats amb dos decimals.


###### MEDIANA SÈPAL

In [7]:
i = 0
longitud_sepal =[fila[i] for fila in arr]
mediana_sepal = np.median(longitud_sepal) 
round(mediana_sepal,2)


5.8

##### DESVIACIÓ SÈPAL

In [8]:
i = 0
longitud_sepal =[fila[i] for fila in arr]
desviacio_sepal = np.std(longitud_sepal) 
round(desviacio_sepal,2)


0.83

###### MEDIANA PÈTAL

In [9]:
i = 2
longitud_petal =[fila[i] for fila in arr]
mediana_petal = np.median(longitud_petal) 
round(mediana_petal,2)

4.35

##### DESVIACIÓ PÈTAL

In [10]:
i = 2
longitud_petal =[fila[i] for fila in arr]
desviacio_petal = np.std(longitud_petal) 
round(desviacio_petal,2)



1.76

### *Exercici 4

##### -Selecciona una mostra aleatòria de 20 registres del conjunt que has obtingut en l'exercici anterior.


In [11]:
from numpy import random

longitud_total = arr.shape[0]
indices_muestra = np.random.choice(longitud_total, 20, replace=False)
muestra_aleatoria = arr[indices_muestra]
print(muestra_aleatoria)

[[6.3 2.3 4.4 1.3 1. ]
 [4.6 3.4 1.4 0.3 0. ]
 [6.  2.7 5.1 1.6 1. ]
 [5.8 2.7 5.1 1.9 2. ]
 [4.8 3.4 1.9 0.2 0. ]
 [6.9 3.1 5.1 2.3 2. ]
 [5.7 4.4 1.5 0.4 0. ]
 [5.2 2.7 3.9 1.4 1. ]
 [6.5 3.2 5.1 2.  2. ]
 [6.7 3.3 5.7 2.5 2. ]
 [6.4 2.7 5.3 1.9 2. ]
 [5.2 3.4 1.4 0.2 0. ]
 [6.4 3.2 5.3 2.3 2. ]
 [6.8 3.  5.5 2.1 2. ]
 [5.8 2.8 5.1 2.4 2. ]
 [6.3 2.8 5.1 1.5 2. ]
 [5.9 3.  4.2 1.5 1. ]
 [6.1 2.6 5.6 1.4 2. ]
 [4.9 3.6 1.4 0.1 0. ]
 [5.6 3.  4.1 1.3 1. ]]


### *Exercici 5
##### -Crea una matriu que mostri: 
###### • La mitjana de cada característica per espècie. 
###### • La desviació estàndard de cada característica per espècie


In [12]:
list(data.target_names)
['setosa', 'versicolor', 'virginica']

['setosa', 'versicolor', 'virginica']

#### MITJANA

In [13]:

valores_unicos = np.unique(muestra_aleatoria[:, -1])


for valor_unico in valores_unicos:
   
    filas_con_valor_unico = muestra_aleatoria[muestra_aleatoria[:, -1] == valor_unico]
    
   
    media_valor = np.mean(filas_con_valor_unico)
    
    print(f'Valor Único: {valor_unico}')
    print(f'Media por especie: {media_valor}')


Valor Único: 0.0
Media por especie: 2.088
Valor Único: 1.0
Media por especie: 3.06
Valor Único: 2.0
Media por especie: 3.7260000000000004


#### DESVIACIÓ

In [79]:
valores_unicos = np.unique(muestra_aleatoria[:, -1])


for valor_unico in valores_unicos:
   
    filas_con_valor_unico = muestra_aleatoria[muestra_aleatoria[:, -1] == valor_unico]
    
   
    desviacion_valor = np.std(filas_con_valor_unico)
    
    print(f'Valor Único: {valor_unico}')
    print(f'Desviación por especie: {desviacion_valor}')

Valor Único: 0.0
Desviación por especie: 1.8815017883573315
Valor Único: 1.0
Desviación por especie: 1.9384014032186418
Valor Único: 2.0
Desviación por especie: 1.9264475077198444


#### *Exercici 6
##### • Calcula la quantitat de mostres per espècie.
##### • Troba l'espècie amb el valor màxim mitjana de la variable "sepal length (cm)"


In [36]:
especies = np.unique(arr[:, -1])

cantidad_muestras_por_especie = {especie: np.sum(arr[:, -1] == especie) for especie in especies}

print(cantidad_muestras_por_especie)

{0.0: 50, 1.0: 50, 2.0: 50}


In [39]:
especies = np.unique(arr[:, -1]) 

mitjanes = []  
for especie in especies:
    mediana_sepal = np.mean(arr[arr[:, -1] == especie][:, 0]) 
    mitjanes.append(mediana_sepal)

especie_max_mitjana = especies[np.argmax(mitjanes)]

print("La especie con el valor medio máximo es:", espècie_max_mitjana)

La especie con el valor medio máximo es: 2.0


### - Exercici 7
###### • Calcula la matriu de correlació entre les variables.
###### • Filtra els valors majors a la mitjana de la longitud dels pètals i mostra-ho. 
###### • Troba la mostra amb els pètals més grans.


In [41]:
# correlacion
np.corrcoef(arr)# Crea matriz de correlación.

array([[1.        , 0.99706483, 0.99997795, ..., 0.73911793, 0.73861621,
        0.72169879],
       [0.99706483, 1.        , 0.99750791, ..., 0.78062955, 0.77554908,
        0.76056628],
       [0.99997795, 0.99750791, 1.        , ..., 0.74245616, 0.74174869,
        0.72472528],
       ...,
       [0.73911793, 0.78062955, 0.74245616, ..., 1.        , 0.99295525,
        0.99565547],
       [0.73861621, 0.77554908, 0.74174869, ..., 0.99295525, 1.        ,
        0.99497962],
       [0.72169879, 0.76056628, 0.72472528, ..., 0.99565547, 0.99497962,
        1.        ]])

In [43]:
# calculando la correlación entre dos vectores.
np.corrcoef(arr[0], arr[1])

array([[1.        , 0.99706483],
       [0.99706483, 1.        ]])

In [47]:
# valores mayor que la mitjana.

longitud_petals = np.array([arr])

mitjana_petals = np.mean(longituds_petals)


valors_major_que_mitjana = longitud_petals[longituds_petals > mitjana_petals]

print(valors_major_que_mitjana)

[5.1 3.5 4.9 3.  4.7 3.2 4.6 3.1 5.  3.6 5.4 3.9 4.6 3.4 5.  3.4 4.4 4.9
 3.1 5.4 3.7 4.8 3.4 4.8 3.  4.3 3.  5.8 4.  5.7 4.4 5.4 3.9 5.1 3.5 5.7
 3.8 5.1 3.8 5.4 3.4 5.1 3.7 4.6 3.6 5.1 3.3 4.8 3.4 5.  3.  5.  3.4 5.2
 3.5 5.2 3.4 4.7 3.2 4.8 3.1 5.4 3.4 5.2 4.1 5.5 4.2 4.9 3.1 5.  3.2 5.5
 3.5 4.9 3.6 4.4 3.  5.1 3.4 5.  3.5 4.5 4.4 3.2 5.  3.5 5.1 3.8 4.8 3.
 5.1 3.8 4.6 3.2 5.3 3.7 5.  3.3 7.  3.2 4.7 6.4 3.2 4.5 6.9 3.1 4.9 5.5
 4.  6.5 4.6 5.7 4.5 6.3 3.3 4.7 4.9 3.3 6.6 4.6 5.2 3.9 5.  3.5 5.9 3.
 4.2 6.  4.  6.1 4.7 5.6 3.6 6.7 3.1 4.4 5.6 3.  4.5 5.8 4.1 6.2 4.5 5.6
 3.9 5.9 3.2 4.8 6.1 4.  6.3 4.9 6.1 4.7 6.4 4.3 6.6 3.  4.4 6.8 4.8 6.7
 3.  5.  6.  4.5 5.7 3.5 5.5 3.8 5.5 3.7 5.8 3.9 6.  5.1 5.4 3.  4.5 6.
 3.4 4.5 6.7 3.1 4.7 6.3 4.4 5.6 3.  4.1 5.5 4.  5.5 4.4 6.1 3.  4.6 5.8
 4.  5.  3.3 5.6 4.2 5.7 3.  4.2 5.7 4.2 6.2 4.3 5.1 3.  5.7 4.1 6.3 3.3
 6.  5.8 5.1 7.1 3.  5.9 6.3 5.6 6.5 3.  5.8 7.6 3.  6.6 4.9 4.5 7.3 6.3
 6.7 5.8 7.2 3.6 6.1 6.5 3.2 5.1 6.4 5.3 6.8 3.  5.5 5

In [50]:

columna_longitud_petalo = 2

indice_fila_max_petalos = np.argmax(arr[:, columna_longitud_petalo])


muestra_max_petalos = arr[indice_fila_max_petalos]

print(muestra_max_petalos)

[7.7 2.6 6.9 2.3 2. ]


### - Exercici 8
##### Troba l'espècie amb la diferència més gran entre la longitud mitjana de sèpals i pètals.


In [68]:
especies = arr[:, -1]
longitud_sepalos = arr[:, 0]
longitud_petalos = arr[:, 2]


longitud_mediana_sepalos = {}
longitud_mediana_petalos = {}

for especie in np.unique(especies):
    longitud_mediana_sepalos[especie] = np.mean(longitud_sepalos)
    longitud_mediana_petalos[especie] = np.mean(longitud_petalos)


diferencia_longitudes = {}

for especie in np.unique(especies):
        diferencia_longitudes[especie] = abs(longitud_mediana_sepalos[especie] - longitud_mediana_petalos[especie])


especie_max_diferencia = max(diferencia_longitudes, key=diferencia_longitudes.get)
maxima_diferencia = diferencia_longitudes[especie_max_diferencia]

print("Especie mayor diferencia:", especie_max_diferencia)
print("Diferencia más grande:", maxima_diferencia)

Especie mayor diferencia: 0.0
Diferencia más grande: 2.0853333333333333
